syntax on
filetype plugin indent on

" Enable gruvbox
set background=dark
set termguicolors
colorscheme gruvbox
" Configuration vim Airline
set laststatus=2
" Backspace
set backspace=2


" Configuration NERDTree
map <F5> :NERDTreeToggle<CR>

" Configuration floaterm
let g:floaterm_keymap_toggle = '<F12>'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.9

" Configuration Vim.FZF
let g:fzf_preview_window = 'right:50%'
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6  }  }



" Trigger configuration. You need to change this to something other than <tab> if you use one of the following:
" - https://github.com/Valloric/YouCompleteMe
" - https://github.com/nvim-lua/completion-nvim
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

set number

"#### STATUSBAR ###############################################
if (&t_Co == 256 || &t_Co == 88) && !has('gui_running')
	set laststatus=2
	set noshowmode
	set statusline=
	set statusline+=%#DiffAdd#%{(mode()=='n')?'\ \ NORMAL\ ':''}
	set statusline+=%#DiffChange#%{(mode()=='i')?'\ \ INSERT\ ':''}
	set statusline+=%#DiffDelete#%{(mode()=='r')?'\ \ RPLACE\ ':''}
	set statusline+=%#Cursor#%{(mode()=='v')?'\ \ VISUAL\ ':''}
	set statusline+=\ %n\           			" buffer number
	set statusline+=%#Visual#       			" colour
	set statusline+=%{&paste?'\ PASTE\ ':''}
	set statusline+=%{&spell?'\ SPELL\ ':''}
	set statusline+=%#CursorIM#     			" colour
	set statusline+=%R                        	" readonly flag
	set statusline+=%M                        	" modified [+] flag
	set statusline+=%#Cursor#               	" colour
	set statusline+=%#CursorLine#     			" colour
	set statusline+=\ %t\                   	" short file name
	set statusline+=%=                          " right align
	set statusline+=%#CursorLine#   			" colour
	set statusline+=\ %Y\                   	" file type
	set statusline+=%#CursorIM#     			" colour
	set statusline+=\ %3l:%-2c\         		" line + column
	set statusline+=%#Cursor#       			" colour
	set statusline+=\ %3p%%\                	" percentage
	"##############################################################
endif
