[main]
font=JetBrainsMono Nerd Font:size=11
pad=8x8

[colors-dark]
# NixOS Dark Slate & Coral Cyan
background=121b20
foreground=d8eeed

regular0=1a262c
regular1=ff4d4d
regular2=54e1b5
regular3=ff9f43
regular4=6fe3e1
regular5=ff6b6b
regular6=5ebcbb
regular7=d8eeed

bright0=334a56
bright1=ff4d4d
bright2=54e1b5
bright3=ff9f43
bright4=6fe3e1
bright5=ff6b6b
bright6=5ebcbb
bright7=ffffff
